# name: Deploy Online

# on:
#   # Only allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#   contents: read
#   pages: write
#   id-token: write

# # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
# concurrency:
#   group: 'telescope'
#   cancel-in-progress: false

# jobs:
#   # Deployment job
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Use private key
#         run: |
#           mkdir -p ~/.ssh
#           echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa

#       - name: Add SSH Key to known_hosts
#         run: |
#           ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

#       - name: Executing remote ssh commands
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_KEY }}
#           script: |
#             cd ~/workspace/telescope
#             npm run deploy
